- resources/public/api/conf/1.0/examples/amend_foreign_property_consolidated_request.json
ENG isn't a valid ISO 3166-1 alpha-3 country code﻿
> updated countryCode in RAML Amend example

- app/v2/controllers/AmendForeignPropertyAnnualSubmissionController.scala
- app/v2/controllers/AmendForeignPropertyPeriodSummaryController.scala
- app/v2/controllers/CreateForeignPropertyPeriodSummaryController.scala
- app/v2/controllers/requestParsers/CreateUkPropertyPeriodSummaryRequestParser.scala
- app/v2/controllers/requestParsers/validators/AmendForeignPropertyAnnualSubmissionValidator.scala
- app/v2/controllers/requestParsers/validators/AmendForeignPropertyPeriodSummaryValidator.scala
- app/v2/controllers/requestParsers/validators/CreateForeignPropertyPeriodSummaryValidator.scala
- app/v2/controllers/requestParsers/validators/CreateUkPropertyPeriodSummaryValidator.scala
- app/v2/controllers/requestParsers/validators/validations/ConsolidatedExpensesValidation.scala
- app/v2/controllers/requestParsers/validators/validations/JsonFormatValidation.scala
- app/v2/models/errors/mtdErrors.scala
- app/v2/models/request/amendForeignPropertyPeriodSummary/AmendForeignPropertyPeriodSummaryRequestBody.scala
- app/v2/models/request/createUkPropertyPeriodSummary/CreateUkPropertyPeriodSummaryRequestBody.scala
- it/v2/endpoints/AmendForeignPropertyAnnualSubmissionControllerISpec.scala
- it/v2/endpoints/AmendForeignPropertyPeriodSummaryControllerISpec.scala
- it/v2/endpoints/CreateForeignPropertyPeriodSummaryControllerISpec.scala
- resources/public/api/conf/2.0/errors.raml
- test/v2/controllers/requestParsers/CreateUkPropertyPeriodSummaryRequestParserSpec.scala
- test/v2/controllers/requestParsers/validators/AmendForeignPropertyAnnualSubmissionValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/AmendForeignPropertyPeriodSummaryValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/CreateForeignPropertyPeriodSummaryValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/CreateUkPropertyPeriodSummaryValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/validations/ConsolidatedExpensesValidationSpec.scala
- test/v2/controllers/requestParsers/validators/validations/JsonFormatValidationSpec.scala
- test/v2/mocks/validators/MockCreateUkPropertyPeriodSummaryValidator.scala
- test/v2/models/utils/JsonErrorValidators.scala
- parser and validator
- fix to v2 foreign endpoints validation tests to include paths that are now included for schema validation
> MTDSA-9944 - create uk property periodic parser and validator

- app/utils/EmptinessChecker.scala
- app/v2/controllers/requestParsers/validators/AmendUkPropertyAnnualSubmissionValidator.scala
- app/v2/controllers/requestParsers/validators/AmendUkPropertyPeriodSummaryValidator.scala
- app/v2/controllers/requestParsers/validators/CreateUkPropertyPeriodSummaryValidator.scala
- app/v2/controllers/requestParsers/validators/validations/JsonFormatValidation.scala
- app/v2/models/request/common/ukPropertyRentARoom/UkPropertyIncomeRentARoom.scala
- app/v2/models/request/createUkPropertyPeriodSummary/CreateUkPropertyPeriodSummaryRequestBody.scala
- test/utils/EmptinessCheckerSpec.scala
- test/v2/controllers/requestParsers/validators/AmendUkPropertyAnnualSubmissionValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/AmendUkPropertyPeriodSummaryValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/CreateUkPropertyPeriodSummaryValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/validations/JsonFormatValidationSpec.scala
> MTDSA-10571 - use generic emptiness check to find paths of empty objects

- app/v2/controllers/AmendUkPropertyAnnualSubmissionController.scala
- app/v2/controllers/requestParsers/validators/AmendForeignPropertyAnnualSubmissionValidator.scala
- app/v2/controllers/requestParsers/validators/AmendUkPropertyAnnualSubmissionValidator.scala
- app/v2/models/errors/mtdErrors.scala
- app/v2/models/response/retrieveForeignPropertyAnnualSubmission/foreignProperty/Building.scala
- app/v2/services/AmendUkPropertyAnnualSubmissionService.scala
- it/v2/endpoints/AmendUkPropertyAnnualSubmissionControllerISpec.scala
- test/v2/controllers/AmendUkPropertyAnnualSubmissionControllerSpec.scala
- test/v2/controllers/requestParsers/validators/AmendForeignPropertyAnnualSubmissionValidatorSpec.scala
- test/v2/controllers/requestParsers/validators/AmendUkPropertyAnnualSubmissionValidatorSpec.scala
- test/v2/services/AmendUkPropertyAnnualSubmissionServiceSpec.scala
- map BUSINESS_VALIDATION_FAILURE to RULE_PROPERTY_INCOME_ALLOWANCE
- validate for RULE_PROPERTY_INCOME_ALLOWANCE
- handle MISSING_ALLOWANCES
- limit both `propertyIncomeAllowance`s to max 1000
> MTDSA-10642 - Alignment Create UK annuals

- app/v2/hateoas/HateoasLinks.scala
- app/v2/models/hateoas/RelType.scala
- app/v2/models/response/createHistoricFhlUkPiePeriodSummary/CreateHistoricFhlUkPiePeriodSummaryResponse.scala
- app/v2/models/response/createHistoricNonFhlUkPiePeriodSummary/CreateHistoricNonFhlUkPiePeriodSummaryResponse.scala
- test/v2/hateoas/HateoasLinksSpec.scala
- test/v2/models/response/createHistoricNonFhlUkPiePeriodSummary/CreateHistoricNonFhlUkPiePeriodSummaryResponseSpec.scala
Response models for CreateHistoricNonFhlUkPiePeriodSummary.
> Response model patch

- app/config/FeatureSwitch.scala
- app/routing/VersionRoutingMap.scala
- conf/application.conf
- conf/v2r7c.routes
- test/config/FeatureSwitchSpec.scala
- test/routing/VersionRoutingMapSpec.scala
- split out new endpoints in routes
- add feature switch
- route based on feature switch
> MTDSA-12325 - feature switch for v2 r7c endpoints

- app/v2/models/request/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryRawData.scala
- app/v2/models/request/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryRequest.scala
- app/v2/models/request/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryRequestBody.scala
- app/v2/models/response/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryResponse.scala
- test/v2/models/request/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryRawDataSpec.scala
- test/v2/models/request/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryRequestBodySpec.scala
- test/v2/models/response/amendHistoricFhlUkPiePeriodSummary/AmendHistoricFhlUkPiePeriodSummaryResponseSpec.scala
Created model for [API.#1429 (#32) - Amend a Historic FHL UK Property Income & Expenses Period Summary](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=476153365)
> Created the model for  API.#1429 (#32) - Amend a Historic FHL UK Property Income & Expenses Period Summary

- app/v2/controllers/requestParsers/DeleteHistoricFhlUkPropertyAnnualSubmissionRequestParser.scala
- app/v2/controllers/requestParsers/validators/DeleteHistoricFhlUkPropertyAnnualSubmissionValidator.scala
- test/v2/controllers/requestParsers/DeleteHistoricFhlUkPropertyAnnualSubmissionRequestParserSpec.scala
- test/v2/controllers/requestParsers/validators/DeleteHistoricFhlUkPropertyAnnualSubmissionValidatorSpec.scala
- test/v2/mocks/validators/MockDeleteHistoricFhlUkPropertyAnnualSubmissionValidator.scala
Parser and validator for Delete Historic FHL Uk Property Annual Submission
> Parser and validator for Delete Historic FHL Uk Property Annual Submission

- resources/public/api/conf/2.0/historic_uk_fhl_period_summary_create.raml
> Updated RAML

- .gitignore
- README.md
- conf/application.conf
- it/config/DocumentationControllerISpec.scala
- resources/public/api/conf/2.0/application.yaml
RAML to OAS migration spike using single yaml file (work in progress)
> [MTDSA-12710] [CK] RAML to OAS migration spike using single yaml file (work in progress)

- app/v2/models/response/listHistoricUkPropertyPeriodSummaries/ListHistoricUkPropertyPeriodSummariesResponse.scala
- app/v2/services/ListHistoricUkPropertyPeriodSummariesService.scala
- it/v2/endpoints/ListHistoricFhlUkPropertyPeriodSummariesControllerISpec.scala
- it/v2/endpoints/ListHistoricNonFhlUkPropertyPeriodSummariesControllerISpec.scala
- test/v2/models/response/listHistoricUkPropertyPeriodSummaries/ListHistoricUkPropertyPeriodSummariesResponseSpec.scala
- test/v2/services/ListHistoricUkPropertyPeriodSummariesServiceSpec.scala
Update code & tests to align with the latest specs.
> [MTDSA-13211] [CK] Update code & tests to align with the latest specs.

- app/v2/connectors/RetrieveUkPropertyPeriodSummaryConnector.scala
- app/v2/controllers/RetrieveUkPropertyPeriodSummaryController.scala
- app/v2/models/errors/mtdErrors.scala
- app/v2/services/RetrieveUkPropertyPeriodSummaryService.scala
- it/v2/endpoints/RetrieveUkPropertyPeriodSummaryControllerISpec.scala
- test/v2/connectors/RetrieveUkPropertyPeriodSummaryConnectorSpec.scala
- test/v2/services/RetrieveUkPropertyPeriodSummaryServiceSpec.scala
This adds TYS functionality to the Retrieve a UK Property Income & Expenses Period Summary - TY (23-24)
Spec here - https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=538346100
> MTDSA-13410

- app/utils/UrlUtils.scala
- app/v2/connectors/BaseDownstreamConnector.scala
- app/v2/connectors/DeletePropertyAnnualSubmissionConnector.scala
- app/v2/controllers/DeletePropertyAnnualSubmissionController.scala
- app/v2/services/DeletePropertyAnnualSubmissionService.scala
- app/v2/services/RetrieveForeignPropertyPeriodSummaryService.scala
- it/v2/endpoints/DeletePropertyAnnualSubmissionControllerISpec.scala
- it/v2/endpoints/RetrieveForeignPropertyPeriodSummaryControllerISpec.scala
- test/mocks/MockHttpClient.scala
- test/utils/UrlUtilsSpec.scala
- test/v2/connectors/ConnectorSpec.scala
- test/v2/connectors/DeletePropertyAnnualSubmissionConnectorSpec.scala
- test/v2/connectors/RetrieveForeignPropertyPeriodSummaryConnectorSpec.scala
- test/v2/controllers/DeletePropertyAnnualSubmissionControllerSpec.scala
- test/v2/controllers/RetrieveForeignPropertyPeriodSummaryControllerSpec.scala
- test/v2/services/DeletePropertyAnnualSubmissionServiceSpec.scala
- test/v2/services/RetrieveForeignPropertyPeriodSummaryServiceSpec.scala
Also a bit of tidying-up in the Retrieve endpoint.
> MTDSA-12956 TYS migration for endpoint: Delete a property annual submission

- resources/public/api/conf/2.0/application.yaml
Spike to merge modular OAS spec files using speccy into a single large OAS spec file.
> [MTDSA-13251] [CK] Spike to merge modular OAS spec files using speccy into a single large OAS spec file.

- it/config/DocumentationControllerISpec.scala
Fix the failing building test error.
> [MTDSA-13251] [CK] Fix the failing building test error.

- app/v2/controllers/CreateAmendHistoricFhlUkPropertyAnnualSubmissionController.scala
- app/v2/models/audit/GenericAuditDetail.scala
- app/v2/services/AuditService.scala
- test/v2/controllers/CreateAmendHistoricFhlUkPropertyAnnualSubmissionControllerSpec.scala
> MTDSA-13719: Added audits for Create and Amend Historic FHL Property Business Annual submission

- app/v2/controllers/CreateAmendHistoricNonFhlUkPropertyAnnualSubmissionController.scala
- app/v2/models/audit/GenericAuditDetail.scala
- test/v2/controllers/CreateAmendHistoricNonFhlUkPropertyAnnualSubmissionControllerSpec.scala
MTDSA-13721 - Audit event for Create & Amend Historic Non Fhl Uk Property Annual
> MTDSA-13721 - Audit event for Create & Amend Historic Non Fhl Uk Property Annual 

- app/v2/controllers/AmendHistoricNonFhlUkPropertyPeriodSummaryController.scala
- test/v2/controllers/AmendHistoricNonFhlUkPropertyPeriodSummaryControllerSpec.scala
MTDSA - 13734 - Added audit event for Amend Historic Non Fhl Uk Property Period Summary
> MTDSA - 13734 - Added audit event for Amend Historic Non Fhl Uk Property Period Summary

- app/v2/controllers/AmendHistoricFhlUkPropertyPeriodSummaryController.scala
- test/v2/controllers/AmendHistoricFhlUkPropertyPeriodSummaryControllerSpec.scala
MTDSA - 13733 - audit event for Amend Historic Fhl Uk Property Period Summary
> MTDSA - 13733 - audit event for Amend Historic Fhl Uk Property Period Summary

- app/v2/controllers/AmendHistoricNonFhlUkPropertyPeriodSummaryController.scala
- test/v2/controllers/AmendHistoricNonFhlUkPropertyPeriodSummaryControllerSpec.scala
MTDSA-13734 - update audit information
> MTDSA-13734 - update audit information

- app/definition/ApiDefinitionFactory.scala
- app/v1/services/EnrolmentsAuthService.scala
- app/v2/services/EnrolmentsAuthService.scala
- it/config/DocumentationControllerISpec.scala
- test/definition/ApiDefinitionFactorySpec.scala
- test/v1/services/EnrolmentsAuthServiceSpec.scala
- test/v2/services/EnrolmentsAuthServiceSpec.scala
Reverts hmrc/property-business-api#349
> Revert "MTDSA-14325 updated confidence level"

- app/v2/controllers/AmendUkPropertyAnnualSubmissionController.scala
- it/config/DocumentationControllerISpec.scala
- project/AppDependencies.scala
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/common/errors.yaml
- resources/public/api/conf/1.0/common/headers.yaml
- resources/public/api/conf/1.0/common/pathParameters.yaml
- resources/public/api/conf/1.0/common/queryParameters.yaml
- resources/public/api/conf/1.0/foreign_property_annual_submission.yaml
- resources/public/api/conf/1.0/foreign_property_annual_submission_amend.yaml
- resources/public/api/conf/1.0/foreign_property_annual_submission_delete.yaml
- resources/public/api/conf/1.0/foreign_property_annual_submission_retrieve.yaml
- resources/public/api/conf/1.0/foreign_property_period_summary.yaml
- resources/public/api/conf/1.0/foreign_property_period_summary_amend.yaml
- resources/public/api/conf/1.0/foreign_property_period_summary_create.yaml
- resources/public/api/conf/1.0/foreign_property_period_summary_list.yaml
- resources/public/api/conf/1.0/foreign_property_period_summary_retrieve.yaml
- resources/public/api/conf/1.0/foreign_property_period_summary_with_submission_id.yaml
- resources/public/api/conf/1.0/schemas/error-response.yaml
It may be worth getting MTDSA-14097 RAML to OAS #355 merged first - we may be able to abstract the v2/errors and v1/errors into one common errors file. Please feel free to review this PR in the meantime too ofc!
> MTDSA-14090 YAML migration for property-business-api v1

- app/config/AppConfig.scala
- app/definition/ApiDefinitionFactory.scala
- conf/application.conf
- it/config/DocumentationControllerISpec.scala
- test/api/services/EnrolmentsAuthServiceSpec.scala
- test/definition/ApiDefinitionFactorySpec.scala
- test/v1/services/EnrolmentsAuthServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/MTDSA-16062
> Make confidence level configurable

- resources/public/api/conf/2.0/uk_property_annual_submission_retrieve.yaml
https://jira.tools.tax.service.gov.uk/browse/MTDSA-16119
> MTDSA-16119 fix documentation

- resources/public/api/conf/2.0/schemas/uk_property_annual_submission_create_and_amend/request.json
- resources/public/api/conf/2.0/schemas/uk_property_annual_submission_retrieve/response.json
https://jira.tools.tax.service.gov.uk/browse/MTDSA-14976
Also some automatic formatting changes. Main change - 
_**Object holding Non UK FHL Rent A Room income shared**_ 
to
_**Object holding UK Non FHL Rent A Room income shared**_
> MTDSA-14976 fix documentation

- app/api/controllers/validators/resolvers/ResolveDateRange.scala
- app/api/controllers/validators/resolvers/ResolveFromAndToDates.scala
- app/api/controllers/validators/resolvers/ResolveParsedNumber.scala
- app/api/controllers/validators/resolvers/ResolverSupport.scala
- app/v2/controllers/validators/CreateForeignPropertyPeriodSummaryRulesValidator.scala
- app/v2/controllers/validators/CreateHistoricFhlUkPiePeriodSummaryValidatorFactory.scala
- app/v2/controllers/validators/CreateHistoricNonFhlUkPropertyPeriodSummaryValidatorFactory.scala
- app/v4/controllers/validators/CreateForeignPropertyPeriodSummaryRulesValidator.scala
- test/api/controllers/validators/resolvers/ResolveDateRangeSpec.scala
- update ResolverSupport to add resolveValid and ResolveParsedNumber to use it
- update ResolveDateRange limit support (required by other APIs) to match BSAS
> MTDSA-19986 - add changes from BSAS

- resources/public/api/conf/5.0/foreign_property_cumulative_summary.yaml
- resources/public/api/conf/5.0/foreign_property_cumulative_summary_create_or_amend.yaml
- resources/public/api/conf/5.0/uk_property_cumulative_summary.yaml
- resources/public/api/conf/5.0/uk_property_cumulative_summary_create_or_amend.yaml
- resources/public/api/conf/6.0/foreign_property_cumulative_summary.yaml
- resources/public/api/conf/6.0/foreign_property_cumulative_summary_create_or_amend.yaml
- resources/public/api/conf/6.0/uk_property_cumulative_summary.yaml
- resources/public/api/conf/6.0/uk_property_cumulative_summary_create_or_amend.yaml
Also renamed the yaml file to prevent future confusion
> [MTDSA-29171] Change 'Create and Amend' to 'Create or Amend' in OAS
